
services:
  app:
    build: .
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:Y1KMJOeDkiqY+r4KEZSWgpTqR60zdQN3ZvYSViNszN8= 
      - DB_CONNECTION=mysql
      - DB_HOST=mysql  # Must match the MySQL service name
      - DB_PORT=3306
      - DB_DATABASE=sahelancedb
      - DB_USERNAME=rootsahelance
      - DB_PASSWORD=SahelanceDBpass12.
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - laravel-network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: SahelanceDBpass12.
      MYSQL_DATABASE: sahelancedb
      MYSQL_USER: rootsahelance
      MYSQL_PASSWORD: SahelanceDBpass12.
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel-network
    command: --default-authentication-plugin=mysql_native_password
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  mysql_data:

networks:
  laravel-network:
    driver: bridge